<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Category;
use Illuminate\Support\Str;

class ProductsTableSeeder extends Seeder
{
    public function run()
    {
        $products = [
            [
                'name' => 'Monstera Deliciosa',
                'description' => 'A beautiful tropical plant perfect for home decoration.',
                'care_instructions' => 'Keep in bright, indirect sunlight. Water when topsoil is dry.',
                'usage' => 'Ideal for living rooms and interior spaces as a statement plant.',
                'price' => 18.00,
                'original_price' => 22.00,
                'image' => 'products/montasera.jpeg',
                'stock' => 20,
                'category_slug' => 'indoor-plants',
            ],
            [
                'name' => 'Peace Lily',
                'description' => 'An elegant indoor plant with white flowers.',
                'care_instructions' => 'Water once a week. Keep soil moist but not soggy.',
                'usage' => 'Perfect for bedrooms and offices, helps purify air.',
                'price' => 14.00,
                'original_price' => 17.00,
                'image' => 'products/peace-lily.jpeg',
                'stock' => 15,
                'category_slug' => 'indoor-plants',
            ],
            [
                'name' => 'Snake Plant',
                'description' => 'Low maintenance indoor plant perfect for beginners.',
                'care_instructions' => 'Tolerates low light. Water every 2–3 weeks.',
                'usage' => 'Best for desks or corners with little sunlight.',
                'price' => 12.00,
                'original_price' => 15.00,
                'image' => 'products/snake-plant.jpeg',
                'stock' => 25,
                'category_slug' => 'indoor-plants',
            ],
            [
                'name' => 'Fiddle Leaf Fig',
                'description' => 'Elegant indoor tree for homes and offices.',
                'care_instructions' => 'Needs bright, indirect light. Water weekly.',
                'usage' => 'Great for modern living rooms as a tall decorative plant.',
                'price' => 20.00,
                'original_price' => 25.00,
                'image' => 'products/fiddle-leaf-fig.webp',
                'stock' => 20,
                'category_slug' => 'indoor-plants',
            ],
            [
                'name' => 'Pothos',
                'description' => 'Trailing plant perfect for hanging baskets.',
                'care_instructions' => 'Water every 1–2 weeks. Thrives in low to medium light.',
                'usage' => 'Perfect for hanging baskets or high shelves.',
                'price' => 7.00,
                'original_price' => 10.00,
                'image' => 'products/pothos.jpeg',
                'stock' => 30,
                'category_slug' => 'indoor-plants',
            ],
            [
                'name' => 'Spider Plant',
                'description' => 'Low maintenance and air purifying plant.',
                'care_instructions' => 'Water once a week. Tolerates a wide range of light.',
                'usage' => 'Excellent for bathrooms or kitchens for fresh air.',
                'price' => 6.50,
                'original_price' => 9.00,
                'image' => 'products/spider-plant.jpeg',
                'stock' => 25,
                'category_slug' => 'indoor-plants',
            ],
            [
                'name' => 'ZZ Plant',
                'description' => 'An easy-care indoor plant perfect for low light.',
                'care_instructions' => 'Water once every 2–3 weeks. Low light friendly.',
                'usage' => 'Great for office desks or dark corners.',
                'price' => 15.00,
                'original_price' => 18.00,
                'image' => 'products/zz-plant.jpeg',
                'stock' => 20,
                'category_slug' => 'indoor-plants',
            ],
            [
                'name' => 'Aloe Vera',
                'description' => 'Medicinal plant with beautiful thick leaves.',
                'care_instructions' => 'Needs direct sunlight. Water every 3 weeks.',
                'usage' => 'Useful for skin treatment and sunburn relief.',
                'price' => 5.00,
                'original_price' => 8.00,
                'image' => 'products/aloe-vera.jpeg',
                'stock' => 25,
                'category_slug' => 'indoor-plants',
            ],
            [
                'name' => 'Chinese Evergreen',
                'description' => 'Attractive foliage perfect for home decoration.',
                'care_instructions' => 'Low light tolerant. Water when soil is dry.',
                'usage' => 'Ideal for entryways or shaded indoor spaces.',
                'price' => 12.00,
                'original_price' => 16.00,
                'image' => 'products/chinese-evergreen.jpeg',
                'stock' => 18,
                'category_slug' => 'indoor-plants',
            ],
        
        

            
            
       // 🌳 Outdoor Plants
       [
        'name' => 'Lemon Tree',
        'description' => 'A small lemon tree ideal for gardens and balconies.',
        'care_instructions' => 'Plant in full sun and water regularly, especially during dry periods.',
        'usage' => 'Perfect for growing your own lemons on balconies or in small gardens.',
        'price' => 25.00,
        'original_price' => 32.00,
        'image' => 'products/lemon-tree.jpg',
        'stock' => 10,
        'category_slug' => 'outdoor-plants',
       ],
    [
        'name' => 'Rose Bush',
        'description' => 'Classic red rose bush for your outdoor space.',
        'care_instructions' => 'Needs full sunlight and deep watering once a week.',
        'usage' => 'Ideal for garden borders or decorative landscaping.',
        'price' => 10.00,
        'original_price' => 14.00,
        'image' => 'products/rose-bush.jpeg',
        'stock' => 18,
        'category_slug' => 'outdoor-plants',
    ],
    [
        'name' => 'Lavender Plant',
        'description' => 'A fragrant lavender plant for your garden.',
        'care_instructions' => 'Requires well-drained soil and full sun. Water sparingly.',
        'usage' => 'Great for fragrance, insect repellent, or dried flower arrangements.',
        'price' => 8.00,
        'original_price' => 12.00,
        'image' => 'products/lavender.jpeg',
        'stock' => 12,
        'category_slug' => 'outdoor-plants',
    ],
    [
        'name' => 'Bamboo Palm',
        'description' => 'Tropical outdoor plant ideal for shade.',
        'care_instructions' => 'Prefers partial shade and consistently moist soil.',
        'usage' => 'Perfect for patios or as a privacy screen in shaded areas.',
        'price' => 18.00,
        'original_price' => 24.00,
        'image' => 'products/bamboo-palm.webp',
        'stock' => 15,
        'category_slug' => 'outdoor-plants',
    ],
    [
        'name' => 'Bougainvillea',
        'description' => 'Vibrant flowering plant for sunny gardens.',
        'care_instructions' => 'Needs full sunlight and minimal watering.',
        'usage' => 'Climbing plant ideal for fences, walls, and pergolas.',
        'price' => 12.00,
        'original_price' => 16.00,
        'image' => 'products/bougainvillea.jpg',
        'stock' => 10,
        'category_slug' => 'outdoor-plants',
    ],
    [
        'name' => 'Hibiscus',
        'description' => 'Tropical beauty for your outdoor spaces.',
        'care_instructions' => 'Water frequently and place in full sunlight.',
        'usage' => 'Great for brightening up outdoor areas with colorful blooms.',
        'price' => 10.00,
        'original_price' => 14.00,
        'image' => 'products/hibiscus.jpeg',
        'stock' => 12,
        'category_slug' => 'outdoor-plants',
    ],
    [
        'name' => 'Olive Tree',
        'description' => 'Mediterranean beauty, ideal for sunny spots.',
        'care_instructions' => 'Needs full sun and well-drained soil. Water moderately.',
        'usage' => 'Can be grown in pots or gardens for a Mediterranean touch.',
        'price' => 30.00,
        'original_price' => 40.00,
        'image' => 'products/olive-tree.jpg',
        'stock' => 12,
        'category_slug' => 'outdoor-plants',
    ],
    [
        'name' => 'Lavender Shrub',
        'description' => 'Fragrant shrub perfect for gardens.',
        'care_instructions' => 'Plant in sunny areas and water only when soil is dry.',
        'usage' => 'Great for borders, walkways, and creating fragrant corners.',
        'price' => 9.00,
        'original_price' => 13.00,
        'image' => 'products/lavender-shrub.jpg',
        'stock' => 20,
        'category_slug' => 'outdoor-plants',
    ],
    [
        'name' => 'Jasmine Plant',
        'description' => 'Beautiful and fragrant outdoor plant.',
        'care_instructions' => 'Needs full to partial sun and regular watering.',
        'usage' => 'Ideal for pergolas and fences, produces a sweet evening fragrance.',
        'price' => 12.00,
        'original_price' => 16.00,
        'image' => 'products/jasmine-plant.jpeg',
        'stock' => 15,
        'category_slug' => 'outdoor-plants',
    ],
            
            
          
    [
        'name' => 'Pruning Shears',
        'description' => 'Essential tool for pruning and cutting plants.',
        'care_instructions' => 'Clean blades after use to prevent rust. Store in a dry place.',
        'usage' => 'Used for trimming dead or overgrown stems and branches.',
        'price' => 6.00,
        'original_price' => 8.00,
        'image' => 'products/pruning-shears.jpeg',
        'stock' => 30,
        'category_slug' => 'gardening-tools',
    ],
    [
        'name' => 'Watering Can',
        'description' => 'A stylish and practical watering can.',
        'care_instructions' => 'Empty after use and store indoors to prevent algae buildup.',
        'usage' => 'Used to water plants evenly, especially potted and indoor plants.',
        'price' => 10.00,
        'original_price' => 13.00,
        'image' => 'products/watering-can.jpeg',
        'stock' => 22,
        'category_slug' => 'gardening-tools',
    ],
    [
        'name' => 'Hand Shovel',
        'description' => 'Perfect tool for small gardening jobs.',
        'care_instructions' => 'Clean soil off after use. Store in a dry shed or box.',
        'usage' => 'Ideal for digging holes and transplanting small plants.',
        'price' => 5.00,
        'original_price' => 7.00,
        'image' => 'products/hand-shovel.jpeg',
        'stock' => 25,
        'category_slug' => 'gardening-tools',
    ],
    [
        'name' => 'Garden Gloves',
        'description' => 'Durable gloves for comfortable gardening.',
        'care_instructions' => 'Wash after use and let dry completely before storing.',
        'usage' => 'Protects hands from dirt, thorns, and chemicals during gardening.',
        'price' => 3.50,
        'original_price' => 5.00,
        'image' => 'products/garden-gloves.webp',
        'stock' => 50,
        'category_slug' => 'gardening-tools',
    ],
    [
        'name' => 'Rake Tool',
        'description' => 'Ideal for clearing leaves and debris.',
        'care_instructions' => 'Remove stuck leaves after use. Keep metal parts dry to prevent rust.',
        'usage' => 'Used to gather leaves, grass, and garden debris from lawns and soil.',
        'price' => 8.00,
        'original_price' => 10.00,
        'image' => 'products/rake.jpeg',
        'stock' => 22,
        'category_slug' => 'gardening-tools',
    ],
    [
        'name' => 'Plant Sprayer',
        'description' => 'Spray mist for delicate plants and seedlings.',
        'care_instructions' => 'Rinse the bottle weekly. Don’t leave liquids inside for long periods.',
        'usage' => 'Sprays a fine mist to keep leaves moist and apply foliar feed.',
        'price' => 5.50,
        'original_price' => 8.00,
        'image' => 'products/plant-sprayer.jpeg',
        'stock' => 30,
        'category_slug' => 'gardening-tools',
    ],
    [
        'name' => 'Hand Fork',
        'description' => 'Essential tool for loosening and turning soil.',
        'care_instructions' => 'Wipe clean after use. Oil metal parts occasionally.',
        'usage' => 'Used to break up soil, mix compost, and weed small areas.',
        'price' => 4.50,
        'original_price' => 6.50,
        'image' => 'products/hand-fork.jpeg',
        'stock' => 25,
        'category_slug' => 'gardening-tools',
    ],
    [
        'name' => 'Garden Trowel',
        'description' => 'Perfect for digging small holes and planting.',
        'care_instructions' => 'Clean blade after each use. Store in a dry toolbox.',
        'usage' => 'Used for planting, digging, or removing weeds.',
        'price' => 5.00,
        'original_price' => 7.00,
        'image' => 'products/garden-trowel.jpg',
        'stock' => 30,
        'category_slug' => 'gardening-tools',
    ],
    [
        'name' => 'Pruning Saw',
        'description' => 'Ideal tool for cutting larger branches.',
        'care_instructions' => 'Wipe blade with oil to prevent rust. Sharpen when needed.',
        'usage' => 'Used to cut thick branches that are too large for pruning shears.',
        'price' => 12.00,
        'original_price' => 15.00,
        'image' => 'products/pruning-saw.jpeg',
        'stock' => 10,
        'category_slug' => 'gardening-tools',
    ],
    
            // soil
           
    [
        'name' => 'Organic Potting Soil (5 KG)',
        'description' => 'High-quality organic soil for potted plants. Bag contains approximately 5 kilograms.',
        'care_instructions' => 'Keep bag sealed and store in a cool, dry place.',
        'usage' => 'Ideal for indoor and outdoor potted plants.',
     
        'price' => 7.00,
        'original_price' => 9.00,
        'image' => 'products/organic-soil.jpeg',
        'stock' => 35,
        'category_slug' => 'soil-fertilizers',
    ],
    [
        'name' => 'Cactus Soil Mix (2 KG)',
        'description' => 'Special soil blend for cactus and succulents. Bag contains approximately 2 kilograms.',
        'care_instructions' => 'Store in dry area to avoid clumping due to moisture.',
        'usage' => 'Designed for cacti, succulents, and other drought-tolerant plants.',
       
        'price' => 4.00,
        'original_price' => 6.00,
        'image' => 'products/cactus-soil.jpg',
        'stock' => 20,
        'category_slug' => 'soil-fertilizers',
    ],
    [
        'name' => 'Natural Fertilizer (5 KG)',
        'description' => 'Boost your plant growth with natural fertilizer. Bag contains approximately 5 kilograms.',
        'care_instructions' => 'Seal after use. Keep out of direct sunlight and moisture.',
        'usage' => 'Suitable for vegetables, herbs, and flowers.',
       
        'price' => 9.00,
        'original_price' => 12.00,
        'image' => 'products/natural-fertilizer.jpg',
        'stock' => 18,
        'category_slug' => 'soil-fertilizers',
    ],
    [
        'name' => 'Potting Mix Bag (3 KG)',
        'description' => 'Rich potting mix ideal for indoor plants. Bag contains approximately 3 kilograms.',
        'care_instructions' => 'Keep bag closed and stored in a dry place.',
        'usage' => 'Best for potted plants and hanging baskets.',
       
        'price' => 5.50,
        'original_price' => 7.50,
        'image' => 'products/potting-mix.jpeg',
        'stock' => 28,
        'category_slug' => 'soil-fertilizers',
    ],
    [
        'name' => 'Vermicompost (5 KG)',
        'description' => 'Natural fertilizer made from earthworms. Bag contains approximately 5 kilograms.',
        'care_instructions' => 'Store in cool, dry area. Avoid moisture exposure.',
        'usage' => 'Excellent for enriching soil in home gardens and pots.',
       
        'price' => 10.00,
        'original_price' => 13.00,
        'image' => 'products/vermicompost.jpeg',
        'stock' => 18,
        'category_slug' => 'soil-fertilizers',
    ],
    [
        'name' => 'Cocopeat Brick (2.5 KG)',
        'description' => 'Eco-friendly growing medium for plants. Brick weight approximately 2.5 kilograms.',
       'care_instructions' => 'Keep in dry storage. Rehydrate only when ready to use.',
        'usage' => 'Use as a base soil enhancer after soaking in water.',
        
        'price' => 4.50,
        'original_price' => 6.50,
        'image' => 'products/cocopeat-brick.jpeg',
        'stock' => 40,
        'category_slug' => 'soil-fertilizers',
    ],
    [
        'name' => 'Perlite Bag (2 KG)',
        'description' => 'Lightweight soil additive for better drainage. Bag contains approximately 2 kilograms.',
        'care_instructions' => 'Seal bag tightly to prevent dust exposure.',
        'usage' => 'Mix with soil to improve aeration and drainage.',
        
        'price' => 5.00,
        'original_price' => 7.00,
        'image' => 'products/perlite-bag.jpeg',
        'stock' => 30,
        'category_slug' => 'soil-fertilizers',
    ],
    [
        'name' => 'Bone Meal Fertilizer (2 KG)',
        'description' => 'Organic fertilizer for strong root growth. Bag contains approximately 2 kilograms.',
         'care_instructions' => 'Store away from pets. Keep in a sealed container.',
        'usage' => 'Best used during planting of bulbs, trees, and shrubs.',
        
        'price' => 6.00,
        'original_price' => 8.00,
        'image' => 'products/bone-meal.jpeg',
        'stock' => 18,
        'category_slug' => 'soil-fertilizers',
    ],
    [
        'name' => 'Organic Compost Mix (5 KG)',
        'description' => 'Premium quality compost to enrich your soil naturally. Bag contains approximately 5 kilograms.',
        'care_instructions' => 'Keep bag sealed to retain nutrients. Store in shade.',
        'usage' => 'Use for soil conditioning and planting beds.',
        
        'price' => 8.00,
        'original_price' => 11.00,
        'image' => 'products/organic-compost-mix.jpg',
        'stock' => 20,
        'category_slug' => 'soil-fertilizers',
    ],
    
    [
        'name' => 'Sunflower Seeds (50g)',
        'description' => 'Grow bright and tall sunflowers easily at home. Packet contains approximately 50 grams.',
        'care_instructions' => 'Store in a cool, dry place away from sunlight.',
        'usage' => 'Plant directly in sunny outdoor spots or large pots.',
       
        'price' => 3.00,
        'original_price' => 4.00,
        'image' => 'products/sunflower-seeds.jpg',
        'stock' => 50,
        'category_slug' => 'seeds',
    ],
    [
        'name' => 'Basil Seeds (20g)',
        'description' => 'Fresh basil seeds for aromatic herbs in your kitchen. Packet contains approximately 20 grams.',
        'care_instructions' => 'Keep sealed in a dry place to maintain freshness.',
        'usage' => 'Ideal for kitchen herb gardens or window boxes.',
        
        'price' => 2.00,
        'original_price' => 3.00,
        'image' => 'products/basil-seeds.jpg',
        'stock' => 40,
        'category_slug' => 'seeds',
    ],
    [
        'name' => 'Tomato Seeds (30g)',
        'description' => 'High-yield tomato seeds for home gardens. Packet contains approximately 30 grams.',
        'care_instructions' => 'Store in a dark, dry space with good air circulation.',
        'usage' => 'Start indoors, then transplant outdoors in full sun.',
        
        'price' => 2.50,
        'original_price' => 3.50,
        'image' => 'products/tomato-seeds.jpg',
        'stock' => 45,
        'category_slug' => 'seeds',
    ],
    [
        'name' => 'Mint Seeds (20g)',
        'description' => 'Easy-to-grow mint seeds perfect for teas and dishes. Packet contains approximately 20 grams.',
        'care_instructions' => 'Seal tightly and store in a dry cabinet.',
        'usage' => 'Grow in containers or garden beds with partial sun.',
        
        'price' => 2.00,
        'original_price' => 3.00,
        'image' => 'products/mint-seeds.jpg',
        'stock' => 35,
        'category_slug' => 'seeds',
    ],
    [
        'name' => 'Carrot Seeds (30g)',
        'description' => 'Organic carrot seeds for a healthy vegetable garden. Packet contains approximately 30 grams.',
        'care_instructions' => 'Keep away from moisture and heat.',
        'usage' => 'Sow directly in well-drained soil outdoors.',
        
        'price' => 2.50,
        'original_price' => 4.00,
        'image' => 'products/carrot-seeds.jpg',
        'stock' => 30,
        'category_slug' => 'seeds',
    ],
    [
        'name' => 'Pepper Seeds (25g)',
        'description' => 'Sweet and spicy pepper seeds for all tastes. Packet contains approximately 25 grams.',
        'care_instructions' => 'Store in airtight bag in a dry place.',
        'usage' => 'Start indoors, transplant after frost risk passes.',
        
        'price' => 2.50,
        'original_price' => 4.00,
        'image' => 'products/pepper-seeds.jpg',
        'stock' => 32,
        'category_slug' => 'seeds',
    ],
    [
        'name' => 'Strawberry Seeds (20g)',
        'description' => 'Grow sweet strawberries right from your garden. Packet contains approximately 20 grams.',
        'care_instructions' => 'Refrigerate if not planting immediately.',
        'usage' => 'Best started indoors, then transplanted to garden or pots.',
       
        'price' => 3.50,
        'original_price' => 5.00,
        'image' => 'products/strawberry-seeds.jpg',
        'stock' => 25,
        'category_slug' => 'seeds',
    ],
    [
        'name' => 'Lavender Seeds (20g)',
        'description' => 'Plant fragrant lavender flowers for relaxation and beauty. Packet contains approximately 20 grams.',
        'care_instructions' => 'Keep cool and dry; use within a year.',
        'usage' => 'Sow in sunny spots or decorative pots.',
        
        'price' => 3.00,
        'original_price' => 4.00,
        'image' => 'products/lavender-seeds.jpg',
        'stock' => 28,
        'category_slug' => 'seeds',
    ],
    [
        'name' => 'Cucumber Seeds (30g)',
        'description' => 'Crispy and fresh cucumber seeds for garden lovers. Packet contains approximately 30 grams.',
        'care_instructions' => 'Seal tightly and store away from humidity.',
        'usage' => 'Plant in warm soil with full sun.',
       
        'price' => 2.50,
        'original_price' => 4.00,
        'image' => 'products/cucumber-seeds.jpg',
        'stock' => 38,
        'category_slug' => 'seeds',
    ],
    
 //pots

    [
        'name' => 'Clay Pot Medium Size',
        'description' => 'Classic medium-sized clay pot, perfect for all types of plants.',
        'care_instructions' => 'Clean with water and mild soap. Avoid freezing temperatures.',
        'usage' => 'Suitable for indoor and outdoor plants. Add drainage layer before soil.',
        'price' => 4.00,
        'original_price' => 6.00,
        'image' => 'products/clay-pot.jpeg',
        'stock' => 20,
        'category_slug' => 'pots',
    ],
    [
        'name' => 'Large Ceramic Planter',
        'description' => 'Beautiful ceramic planter for large plants and indoor trees.',
        'care_instructions' => 'Wipe with a damp cloth. Avoid dropping or harsh impacts.',
        'usage' => 'Ideal for big houseplants or decorative indoor trees.',
        'price' => 8.00,
        'original_price' => 12.00,
        'image' => 'products/ceramic-planter.jpeg',
        'stock' => 10,
        'category_slug' => 'pots',
    ],
    [
        'name' => 'Hanging Pot Set',
        'description' => 'Set of 3 hanging pots for balconies and patios.',
        'care_instructions' => 'Check the hanging cords regularly. Clean with soft cloth.',
        'usage' => 'Hang on balcony railings or ceiling hooks. Best for trailing plants.',
        'price' => 6.00,
        'original_price' => 8.00,
        'image' => 'products/hanging-pot.jpeg',
        'stock' => 12,
        'category_slug' => 'pots',
    ],
    [
        'name' => 'Decorative Plastic Pot',
        'description' => 'Lightweight and colorful pot perfect for decorative plants.',
        'care_instructions' => 'Wash with water. Avoid direct sun to prevent fading.',
        'usage' => 'Great for lightweight plants. Use indoors or on shelves.',
        'price' => 3.50,
        'original_price' => 5.00,
        'image' => 'products/plastic-pot.jpeg',
        'stock' => 30,
        'category_slug' => 'pots',
    ],
    [
        'name' => 'Modern Metal Planter',
        'description' => 'Stylish metal planter for modern interiors.',
        'care_instructions' => 'Wipe with dry cloth. Keep away from water to avoid rust.',
        'usage' => 'Perfect for minimalist indoor designs. Use with plastic inner pot.',
        'price' => 10.00,
        'original_price' => 15.00,
        'image' => 'products/metal-planter.jpeg',
        'stock' => 8,
        'category_slug' => 'pots',
    ],
    [
        'name' => 'Terracotta Pot',
        'description' => 'Classic clay pot for any plant type.',
        'care_instructions' => 'Soak before use. Clean with brush. Store indoors in winter.',
        'usage' => 'Ideal for herbs and flowering plants. Allows natural aeration.',
        'price' => 5.00,
        'original_price' => 7.00,
        'image' => 'products/terracotta-pot.jpeg',
        'stock' => 40,
        'category_slug' => 'pots',
    ],
    [
        'name' => 'Self-Watering Planter',
        'description' => 'Smart pot with a self-watering system.',
        'care_instructions' => 'Clean the water reservoir monthly. Avoid algae buildup.',
        'usage' => 'Perfect for busy plant owners. Fill reservoir every few days.',
        'price' => 7.50,
        'original_price' => 10.00,
        'image' => 'products/self-watering-planter.jpeg',
        'stock' => 20,
        'category_slug' => 'pots',
    ],
    [
        'name' => 'Concrete Planter',
        'description' => 'Modern stylish planter for indoor & outdoor use.',
        'care_instructions' => 'Avoid dropping. Clean with a damp cloth. Seal if needed.',
        'usage' => 'Use for large plants or decorative displays. Heavy and stable.',
        'price' => 8.00,
        'original_price' => 10.00,
        'image' => 'products/concrete-planter.jpeg',
        'stock' => 15,
        'category_slug' => 'pots',
    ],
    [
        'name' => 'Hanging Basket',
        'description' => 'Perfect for small balconies and patios.',
        'care_instructions' => 'Keep cords dry. Remove and clean basket monthly.',
        'usage' => 'Ideal for flowering or trailing plants. Hang in partial sun.',
        'price' => 5.00,
        'original_price' => 7.00,
        'image' => 'products/hanging-basket.jpeg',
        'stock' => 25,
        'category_slug' => 'pots',
    ],
    

// kids garden 
[
    'name' => 'Kids Mini Watering Can - Small Size',
    'description' => 'Colorful lightweight watering can perfect for little hands.',
    'care_instructions' => null,
    'usage' => null,
    'price' => 4.00,
    'original_price' => 6.00,
    'image' => 'products/kids-watering-can1.jpeg',
    'stock' => 30,
    'category_slug' => 'kids-gardening',
],
[
    'name' => 'Children Gardening Gloves',
    'description' => 'Soft and durable gloves to protect little gardeners.',
    'care_instructions' => null,
    'usage' => null,
    'price' => 3.50,
    'original_price' => 5.00,
    'image' => 'products/kids-gardening-gloves.jpeg',
    'stock' => 40,
    'category_slug' => 'kids-gardening',
],
[
    'name' => 'Kids Gardening Tool Set',
    'description' => 'A colorful mini tool set including shovel, rake, and trowel.',
    'care_instructions' => null,
    'usage' => null,
    'price' => 8.00,
    'original_price' => 12.00,
    'image' => 'products/kids-tool-set.jpeg',
    'stock' => 25,
    'category_slug' => 'kids-gardening',
],
[
    'name' => 'Flower Growing Kit for Kids',
    'description' => 'A complete kit for kids to grow their own flowers easily.',
    'care_instructions' => null,
    'usage' => null,
    'price' => 10.00,
    'original_price' => 12.00,
    'image' => 'products/kids-flower-growing-kit.jpeg',
    'stock' => 18,
    'category_slug' => 'kids-gardening',
],
[
    'name' => 'Kids Mini Watering Can',
    'description' => 'Colorful lightweight watering can perfect for little hands.',
    'care_instructions' => null,
    'usage' => null,
    'price' => 4.00,
    'original_price' => 6.00,
    'image' => 'products/kids-watering-can.jpeg',
    'stock' => 30,
    'category_slug' => 'kids-gardening',
],
[
    'name' => 'Mini Plant Pots for Kids',
    'description' => 'Set of colorful small pots designed for kids\' projects.',
    'care_instructions' => null,
    'usage' => null,
    'price' => 6.00,
    'original_price' => 8.00,
    'image' => 'products/kids-mini-pots.jpeg',
    'stock' => 30,
    'category_slug' => 'kids-gardening',
],
[
    'name' => 'Kids Grow Your Own Vegetables Kit',
    'description' => 'Fun vegetable growing kit to teach kids about gardening.',
    'care_instructions' => null,
    'usage' => null,
    'price' => 8.00,
    'original_price' => 10.00,
    'image' => 'products/kids-vegetable-growing-kit.jpeg',
    'stock' => 22,
    'category_slug' => 'kids-gardening',
],
[
    'name' => 'Paint Your Own Flower Pot Kit',
    'description' => 'Creative kit for kids to paint and customize flower pots.',
    'care_instructions' => null,
    'usage' => null,
    'price' => 7.50,
    'original_price' => 9.00,
    'image' => 'products/kids-paint-flower-pot.jpeg',
    'stock' => 20,
    'category_slug' => 'kids-gardening',
],
[
    'name' => 'Little Gardeners Starter Kit',
    'description' => 'Complete starter gardening kit perfect for young kids.',
    'care_instructions' => null,
    'usage' => null,
    'price' => 10.00,
    'original_price' => 12.00,
    'image' => 'products/kids-gardener-starter-kit.jpg',
    'stock' => 15,
    'category_slug' => 'kids-gardening',
],
            
            
            
        ];

        foreach ($products as $productData) {
            $category = Category::where('slug', $productData['category_slug'])->first();
            if ($category) {
                Product::create([
                    'name' => $productData['name'],
                    'slug' => Str::slug($productData['name']),
                    'description' => $productData['description'],
                    'care_instructions' => $productData['care_instructions'] ?? null, // إضافة طريقة العناية
                    'usage' => $productData['usage'] ?? null, // إضافة طريقة الاستخدام
                    'price' => $productData['price'],
                    'original_price' => $productData['original_price'] ?? null,
                    'image' => $productData['image'],
                    'images' => $productData['images'] ?? null, // إضافة الصور المتعددة (اختياري)
                    'is_featured' => rand(0, 1),
                    'is_hot' => rand(0, 1),
                    'is_on_sale' => rand(0, 1),
                    'stock' => $productData['stock'],
                    'category_id' => $category->id,
                ]);
            }
        }
        
    }
}
