<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Category;
use Illuminate\Support\Str;

class ProductsTableSeeder extends Seeder
{
    public function run()
    {
        $products = [
            [
                'name' => 'Monstera Deliciosa',
                'description' => "Monstera Deliciosa, also known as the Swiss Cheese Plant, is a stunning tropical plant with large, split leaves. It’s perfect for adding a bold, exotic touch to your home decor and makes a great statement in living rooms or spacious interiors.\n\nHeight: 90 cm\nWidth: 60 cm",
                'care_instructions' => "• Light: Needs bright, indirect sunlight. Avoid direct sun which can burn the leaves.\n• Water: Water when the top 2–3 cm of soil is dry. Ensure proper drainage to prevent root rot.\n• Humidity: Loves high humidity. Mist the leaves regularly to keep them fresh.\n• Soil: Use well-draining soil, ideally a mix of peat moss and perlite.",
                'usage' => 'Ideal for living rooms and interior spaces as a statement plant.',
                'price' => 18.00,
                'original_price' => 22.00,
                'image' => 'products/montasera.jpeg',
                'stock' => 20,
                'category_slug' => 'indoor-plants',
            ],
            [
                'name' => 'Peace Lily',
                'description' => "The Peace Lily is an elegant indoor plant known for its white blossoms and deep green foliage. It helps purify indoor air, making it ideal for bedrooms and workspaces.\n\nHeight: 65 cm\nWidth: 40 cm",
                'care_instructions' => "• Light: Thrives in low to moderate light. Avoid direct sunlight.\n• Water: Water once a week and keep the soil moist but not soggy.\n• Humidity: Prefers a humid environment. Mist occasionally.\n• Caution: Leaves are toxic to pets—keep out of reach.",
                'usage' => 'Perfect for bedrooms and offices, helps purify air.',
                'price' => 14.00,
                'original_price' => 17.00,
                'image' => 'products/peace-lily.jpeg',
                'stock' => 15,
                'category_slug' => 'indoor-plants',
            ],
            [
                'name' => 'Snake Plant',
                'description' => "The Snake Plant, or Sansevieria, is one of the easiest houseplants to care for. With its tall, upright leaves, it's great for modern interior design and perfect for beginners.\n\nHeight: 75 cm\nWidth: 25 cm",
                'care_instructions' => "• Light: Tolerates low light but grows best in medium to bright light.\n• Water: Water every 2–3 weeks and allow the soil to dry completely between waterings.\n• Air: Prefers drier environments. No need for high humidity.\n• Soil: Use well-draining soil, ideally mixed with sand or small gravel.",
                'usage' => 'Best for desks or corners with little sunlight.',
                'price' => 12.00,
                'original_price' => 15.00,
                'image' => 'products/snake-plant.jpeg',
                'stock' => 25,
                'category_slug' => 'indoor-plants',
            ],
        


        
   [
    'name' => 'Fiddle Leaf Fig',
    'description' => "The Fiddle Leaf Fig is a stylish and elegant indoor tree with large, violin-shaped leaves. It adds height and a bold statement to modern interiors, especially in corners and open spaces.\n\nHeight: 120 cm\nWidth: 70 cm",
    'care_instructions' => "• Light: Prefers bright, indirect sunlight. Rotate the plant occasionally for even growth.\n• Water: Water once a week, allowing the top 2–3 cm of soil to dry between waterings.\n• Humidity: Enjoys moderate to high humidity. Misting can help in dry climates.\n• Soil: Use well-draining potting mix with good aeration.",
    'usage' => 'Great for modern living rooms as a tall decorative plant.',
    'price' => 20.00,
    'original_price' => 25.00,
    'image' => 'products/fiddle-leaf-fig.webp',
    'stock' => 20,
    'category_slug' => 'indoor-plants',
],
[
    'name' => 'Pothos',
    'description' => "Pothos is a versatile trailing plant with heart-shaped leaves that come in various shades of green. It’s ideal for hanging baskets or letting it trail off shelves, giving your space a lush, jungle feel.\n\nHeight: 25 cm (trailing up to 100 cm)\nWidth: 30 cm",
    'care_instructions' => "• Light: Thrives in low to medium indirect light, but can tolerate low light.\n• Water: Water every 1–2 weeks, allowing the soil to dry out between waterings.\n• Humidity: Adapts well to average household humidity.\n• Soil: Prefers well-draining potting soil. Avoid waterlogging.",
    'usage' => 'Perfect for hanging baskets or high shelves.',
    'price' => 7.00,
    'original_price' => 10.00,
    'image' => 'products/pothos.jpeg',
    'stock' => 30,
    'category_slug' => 'indoor-plants',
],
[
    'name' => 'Spider Plant',
    'description' => "The Spider Plant is a classic favorite for its arching green and white striped leaves and air-purifying qualities. It's beginner-friendly and adds a fresh touch to kitchens and bathrooms.\n\nHeight: 35 cm\nWidth: 40 cm",
    'care_instructions' => "• Light: Tolerates a wide range of light, but prefers bright, indirect light.\n• Water: Water once a week, and allow soil to dry slightly between waterings.\n• Humidity: Adapts well to most indoor conditions, but appreciates occasional misting.\n• Soil: Use light, well-draining soil. Avoid soggy roots.",
    'usage' => 'Excellent for bathrooms or kitchens for fresh air.',
    'price' => 6.50,
    'original_price' => 9.00,
    'image' => 'products/spider-plant.jpeg',
    'stock' => 25,
    'category_slug' => 'indoor-plants',
],





          [
    'name' => 'ZZ Plant',
    'description' => "The ZZ Plant is a super low-maintenance indoor plant with shiny, dark green leaves that bring a modern touch to your space. It's resilient and thrives in low light, making it a favorite for offices and minimalist homes.\n\nHeight: 55 cm\nWidth: 35 cm",
    'care_instructions' => "• Light: Thrives in low to moderate light. No direct sunlight needed.\n• Water: Water once every 2–3 weeks, letting the soil dry out completely between waterings.\n• Humidity: Tolerates dry air. No special humidity needs.\n• Soil: Use well-draining soil, such as cactus mix or potting soil with perlite.",
    'usage' => 'Great for office desks or dark corners.',
    'price' => 15.00,
    'original_price' => 18.00,
    'image' => 'products/zz-plant.jpeg',
    'stock' => 20,
    'category_slug' => 'indoor-plants',
],
[
    'name' => 'Aloe Vera',
    'description' => "Aloe Vera is a succulent plant known for its medicinal properties and sculptural, thick green leaves. It’s not just pretty—it’s useful for treating burns, cuts, and dry skin!\n\nHeight: 35 cm\nWidth: 25 cm",
    'care_instructions' => "• Light: Loves bright, direct sunlight. A sunny windowsill is perfect.\n• Water: Water every 3 weeks, and even less in winter. Allow the soil to dry out completely.\n• Humidity: Prefers dry environments. No misting needed.\n• Soil: Needs sandy, well-draining soil like cactus mix.",
    'usage' => 'Useful for skin treatment and sunburn relief.',
    'price' => 5.00,
    'original_price' => 8.00,
    'image' => 'products/aloe-vera.jpeg',
    'stock' => 25,
    'category_slug' => 'indoor-plants',
],
[
    'name' => 'Chinese Evergreen',
    'description' => "The Chinese Evergreen is a gorgeous, slow-growing houseplant with patterned leaves that bring elegance to any space. It’s super adaptable and thrives even in less-than-ideal conditions.\n\nHeight: 60 cm\nWidth: 45 cm",
    'care_instructions' => "• Light: Tolerates low light but prefers medium, indirect light.\n• Water: Water when the top layer of soil (2–3 cm) feels dry.\n• Humidity: Enjoys average humidity, but can adapt to dry air.\n• Soil: Use a rich, well-draining potting mix.",
    'usage' => 'Ideal for entryways or shaded indoor spaces.',
    'price' => 12.00,
    'original_price' => 16.00,
    'image' => 'products/chinese-evergreen.jpeg',
    'stock' => 18,
    'category_slug' => 'indoor-plants',
],

        

            
            
       // 🌳 Outdoor Plants
       [
        'name' => 'Lemon Tree',
        'description' => "A small lemon tree that’s perfect for balconies and small gardens. Not only does it add greenery to your space, but it also produces fresh, home-grown lemons!\n\nHeight: 90 cm\nWidth: 60 cm",
        'care_instructions' => "• Light: Requires full sun (at least 6 hours daily).\n• Water: Water regularly, especially during hot and dry periods.\n• Humidity: Prefers moderate humidity but adapts to outdoor conditions.\n• Soil: Needs well-draining soil enriched with organic compost.",
        'usage' => 'Perfect for growing your own lemons on balconies or in small gardens.',
        'price' => 25.00,
        'original_price' => 32.00,
        'image' => 'products/lemon-tree.jpg',
        'stock' => 10,
        'category_slug' => 'outdoor-plants',
    ],
    [
        'name' => 'Rose Bush',
        'description' => "A classic red rose bush that brings romance and beauty to any outdoor space. With proper care, it blooms generously throughout the season.\n\nHeight: 70 cm\nWidth: 50 cm",
        'care_instructions' => "• Light: Needs full sun for at least 6 hours daily.\n• Water: Deep watering once a week; more in hot weather.\n• Humidity: Tolerates outdoor humidity levels.\n• Soil: Prefers rich, well-drained soil. Add mulch to retain moisture.",
        'usage' => 'Ideal for garden borders or decorative landscaping.',
        'price' => 10.00,
        'original_price' => 14.00,
        'image' => 'products/rose-bush.jpeg',
        'stock' => 18,
        'category_slug' => 'outdoor-plants',
    ],
    [
        'name' => 'Lavender Plant',
        'description' => "A fragrant lavender plant that adds beauty and a soothing scent to your garden. It’s low maintenance and also useful as a natural insect repellent.\n\nHeight: 60 cm\nWidth: 50 cm",
        'care_instructions' => "• Light: Requires full sun.\n• Water: Water sparingly; let the soil dry between watering.\n• Humidity: Prefers dry to moderate humidity.\n• Soil: Needs well-drained, slightly sandy soil.",
        'usage' => 'Great for fragrance, insect repellent, or dried flower arrangements.',
        'price' => 8.00,
        'original_price' => 12.00,
        'image' => 'products/lavender-shrub.jpg',
        'stock' => 12,
        'category_slug' => 'outdoor-plants',
    ],
    [
        'name' => 'Bamboo Palm',
        'description' => "A lush, tropical outdoor plant that thrives in shaded areas. It adds a peaceful, exotic touch to any patio or garden.\n\nHeight: 100 cm\nWidth: 70 cm",
        'care_instructions' => "• Light: Prefers partial shade.\n• Water: Keep soil consistently moist but not soggy.\n• Humidity: Enjoys high humidity; mist occasionally in dry climates.\n• Soil: Use a rich, moisture-retaining soil mix.",
        'usage' => 'Perfect for patios or as a privacy screen in shaded areas.',
        'price' => 18.00,
        'original_price' => 24.00,
        'image' => 'products/bamboo-palm.webp',
        'stock' => 15,
        'category_slug' => 'outdoor-plants',
    ],

    
    [
        'name' => 'Bougainvillea',
        'description' => "A vibrant flowering plant that adds bursts of color to sunny gardens. Known for its paper-like petals and climbing growth habit.\n\nHeight: 90 cm\nWidth: 70 cm",
        'care_instructions' => "• Light: Requires full sunlight to thrive.\n• Water: Water sparingly; allow the soil to dry out between watering.\n• Humidity: Adapts well to dry outdoor conditions.\n• Soil: Needs well-drained, slightly sandy soil.",
        'usage' => 'Climbing plant ideal for fences, walls, and pergolas.',
        'price' => 7.50,
        'original_price' => 10.00,
        'image' => 'products/bougainvillea.jpg',
        'stock' => 10,
        'category_slug' => 'outdoor-plants',
    ],
    
    [
        'name' => 'Hibiscus',
        'description' => "A tropical beauty with large, colorful blooms that bring life and color to any outdoor space.\n\nHeight: 80 cm\nWidth: 60 cm",
        'care_instructions' => "• Light: Needs full sunlight for optimal flowering.\n• Water: Water frequently, especially in warmer months.\n• Humidity: Prefers moderate to high humidity.\n• Soil: Grows best in well-drained, fertile soil enriched with compost.",
        'usage' => 'Great for brightening up outdoor areas with colorful blooms.',
        'price' => 10.00,
        'original_price' => 14.00,
        'image' => 'products/hibiscus.jpeg',
        'stock' => 12,
        'category_slug' => 'outdoor-plants',
    ],
    
    [
        'name' => 'Olive Tree',
        'description' => "Bring a Mediterranean touch to your space with this elegant and drought-tolerant tree. A timeless symbol of peace and nature.\n\nHeight: 100 cm\nWidth: 70 cm",
        'care_instructions' => "• Light: Requires full sun.\n• Water: Water moderately and allow soil to dry out between watering.\n• Humidity: Tolerates dry outdoor air.\n• Soil: Needs well-drained, slightly alkaline soil.",
        'usage' => 'Can be grown in pots or gardens for a Mediterranean touch.',
        'price' => 30.00,
        'original_price' => 40.00,
        'image' => 'products/olive-tree.jpg',
        'stock' => 12,
        'category_slug' => 'outdoor-plants',
    ],
    
    [
        'name' => 'Lavender Shrub',
        'description' => "A fragrant and hardy shrub that brings calming aromas and charming color to any garden.\n\nHeight: 65 cm\nWidth: 55 cm",
        'care_instructions' => "• Light: Prefers full sun.\n• Water: Water only when the soil is completely dry.\n• Humidity: Best in dry to moderate climates.\n• Soil: Requires well-draining, sandy or gravelly soil.",
        'usage' => 'Great for borders, walkways, and creating fragrant corners.',
        'price' => 11.00,
        'original_price' => 15.00,
        'image' => 'products/lavender.jpeg',
        'stock' => 20,
        'category_slug' => 'outdoor-plants',
        
    ],
    
    [
        'name' => 'Jasmine Plant',
        'description' => "A beautifully fragrant climbing plant that blooms in warm weather and fills the air with a sweet scent, especially in the evening.\n\nHeight: 90 cm\nWidth: 60 cm",
        'care_instructions' => "• Light: Needs full to partial sun.\n• Water: Water regularly, especially during dry periods.\n• Humidity: Enjoys moderate humidity and good airflow.\n• Soil: Grows best in rich, well-draining soil.",
        'usage' => 'Ideal for pergolas and fences, produces a sweet evening fragrance.',
        'price' => 12.00,
        'original_price' => 16.00,
        'image' => 'products/jasmine-plant.jpeg',
        'stock' => 15,
        'category_slug' => 'outdoor-plants',
    ],
    
        
    // tools
          
    
        [
            'name' => 'Pruning Shears',
            'description' => "Medium-sized pruning shears (Length: 20 cm, Width: 5.5 cm). An essential tool for precise trimming and cutting of plants, dead stems, and overgrown branches.",
            'care_instructions' => "• Wipe the blades clean after each use with a damp cloth.\n• Apply light oil on the blades weekly to prevent rust.\n• Keep them locked and store in a dry, cool place.",
            'usage' => 'Perfect for shaping shrubs and maintaining plant health.',
            'price' => 6.00,
            'original_price' => 8.00,
            'image' => 'products/pruning-shears.jpeg',
            'stock' => 30,
            'category_slug' => 'gardening-tools',
        ],
        [
            'name' => 'Watering Can',
            'description' => "Medium watering can (Height: 25 cm, Width: 12 cm). Stylish and practical, designed for evenly distributing water to both indoor and outdoor plants.",
            'care_instructions' => "• Empty the can completely after every use.\n• Rinse the inside with clean water weekly to prevent algae.\n• Store indoors to avoid damage from direct sunlight and temperature changes.",
            'usage' => 'Ensures soft water flow, great for delicate plants.',
            'price' => 4.00,
            'original_price' => 7.00,
            'image' => 'products/watering-can.jpeg',
            'stock' => 22,
            'category_slug' => 'gardening-tools',
        ],
        [
            'name' => 'Hand Shovel',
            'description' => "Medium hand shovel (Length: 28 cm, Blade Width: 8 cm). Compact and strong, ideal for planting, digging, and transplanting in flower beds or pots.",
            'care_instructions' => "• Brush off soil after every use.\n• Dry the blade thoroughly to prevent rust.\n• Store in a shed or toolbox, away from moisture.",
            'usage' => 'Helps in digging holes, moving soil, and small landscaping tasks.',
            'price' => 5.00,
            'original_price' => 7.00,
            'image' => 'products/hand-shovel.jpeg',
            'stock' => 25,
            'category_slug' => 'gardening-tools',
        ],
        [
            'name' => 'Garden Gloves',
            'description' => "Medium garden gloves (Length: 24 cm, Palm Width: 10 cm). Durable and comfortable gloves that protect hands from dirt, thorns, and chemicals.",
            'care_instructions' => "• Wash with mild soap after every use.\n• Let air dry completely before storing.\n• Avoid storing in damp places to prevent mold and odor.",
            'usage' => 'Ideal for all general gardening tasks.',
            'price' => 3.50,
            'original_price' => 5.00,
            'image' => 'products/garden-gloves.webp',
            'stock' => 50,
            'category_slug' => 'gardening-tools',
        ],
        [
            'name' => 'Rake Tool',
            'description' => "Medium rake (Length: 110 cm, Head Width: 30 cm). Designed for clearing leaves, grass, and debris efficiently from gardens or lawns.",
            'care_instructions' => "• Remove stuck leaves and dirt from the head.\n• Wipe the metal parts and dry them well.\n• Store upright in a dry garage or shed to prevent rust.",
            'usage' => 'Keeps your garden tidy and aerated.',
            'price' => 8.00,
            'original_price' => 10.00,
            'image' => 'products/rake.jpeg',
            'stock' => 22,
            'category_slug' => 'gardening-tools',
        ],
        [
            'name' => 'Plant Sprayer',
            'description' => "Medium plant sprayer (Height: 22 cm, Width: 9 cm). Provides a fine mist perfect for keeping leaves fresh and applying foliar feed.",
            'care_instructions' => "• Rinse the bottle weekly with warm water.\n• Avoid leaving liquid inside for more than a day or two.\n• Store in a cool, shaded area.",
            'usage' => 'Great for seedlings and humidity-loving plants.',
            'price' => 5.50,
            'original_price' => 8.00,
            'image' => 'products/plant-sprayer.jpeg',
            'stock' => 30,
            'category_slug' => 'gardening-tools',
        ],
        [
            'name' => 'Hand Fork',
            'description' => "Medium hand fork (Length: 27 cm, Head Width: 7.5 cm). Sturdy and efficient for loosening soil, mixing compost, and weeding.",
            'care_instructions' => "• Wipe the tines clean after every use.\n• Occasionally oil the metal to maintain condition.\n• Hang or store in a dry place.",
            'usage' => 'Ideal for working soil in small garden beds or containers.',
            'price' => 4.50,
            'original_price' => 6.50,
            'image' => 'products/hand-fork.jpeg',
            'stock' => 25,
            'category_slug' => 'gardening-tools',
        ],
        [
            'name' => 'Garden Trowel',
            'description' => "Medium garden trowel (Length: 26 cm, Blade Width: 7.5 cm). A multipurpose hand tool for digging, planting, and removing weeds.",
            'care_instructions' => "• Clean off soil and sap from the blade.\n• Dry and oil the blade to protect from rust.\n• Store in a dry container or toolbox.",
            'usage' => 'Used for planting, digging, or removing weeds.',
            'price' => 5.00,
            'original_price' => 7.00,
            'image' => 'products/garden-trowel.jpg',
            'stock' => 30,
            'category_slug' => 'gardening-tools',
        ],
        [
            'name' => 'Pruning Saw',
            'description' => "Medium pruning saw (Length: 35 cm, Blade Width: 3.5 cm). Sharp and strong, built for cutting through thick branches where shears fall short.",
            'care_instructions' => "• Clean blade after each use with a dry cloth.\n• Apply blade oil regularly to prevent rust.\n• Sharpen blade periodically and store in a protective sheath.",
            'usage' => 'Used to cut thick branches that are too large for pruning shears.',
            'price' => 4.00,
            'original_price' => 7.00,
            'image' => 'products/pruning-saw.jpeg',
            'stock' => 10,
            'category_slug' => 'gardening-tools',
        ],
    
    
    
            // soil
           
  [
    'name' => 'Organic Potting Soil (5 KG)',
    'description' => 'High-quality organic soil perfect for potted plants. Each 5 KG bag is rich in nutrients and organic matter to support healthy plant growth and moisture retention. Ideal for both indoor and outdoor use.',
    'care_instructions' => 'Keep bag sealed and store in a cool, dry place.',
    'usage' => 'Ideal for indoor and outdoor potted plants.',
    'price' => 7.00,
    'original_price' => 9.00,
    'image' => 'products/organic-soil.jpeg',
    'stock' => 35,
    'category_slug' => 'soil-fertilizers',
],
[
    'name' => 'Cactus Soil Mix (2 KG)',
    'description' => 'Specially formulated soil mix for cacti and succulents. This 2 KG bag contains a well-draining blend that prevents root rot and promotes healthy growth for drought-tolerant plants.',
    'care_instructions' => 'Store in dry area to avoid clumping due to moisture.',
    'usage' => 'Designed for cacti, succulents, and other drought-tolerant plants.',
    'price' => 4.00,
    'original_price' => 6.00,
    'image' => 'products/cactus-soil.jpg',
    'stock' => 20,
    'category_slug' => 'soil-fertilizers',
],
[
    'name' => 'Natural Fertilizer (5 KG)',
    'description' => 'Boost your plant growth naturally! This 5 KG bag contains a blend of essential nutrients like nitrogen and phosphorus, perfect for vegetables, herbs, and flowers. Safe and effective for home gardening.',
    'care_instructions' => 'Seal after use. Keep out of direct sunlight and moisture.',
    'usage' => 'Suitable for vegetables, herbs, and flowers.',
    'price' => 9.00,
    'original_price' => 12.00,
    'image' => 'products/natural-fertilizer.jpg',
    'stock' => 18,
    'category_slug' => 'soil-fertilizers',
],
[
    'name' => 'Potting Mix Bag (3 KG)',
    'description' => 'Rich and balanced potting mix designed for indoor plants. The 3 KG bag is ideal for potted plants and hanging baskets, providing nutrients and moisture retention for healthy growth.',
    'care_instructions' => 'Keep bag closed and stored in a dry place.',
    'usage' => 'Best for potted plants and hanging baskets.',
    'price' => 5.50,
    'original_price' => 7.50,
    'image' => 'products/potting-mix.jpeg',
    'stock' => 28,
    'category_slug' => 'soil-fertilizers',
],
[
    'name' => 'Vermicompost (5 KG)',
    'description' => 'Organic fertilizer produced by earthworms! This 5 KG bag is packed with beneficial microbes and nutrients that improve soil structure and fertility, perfect for pots and garden beds.',
    'care_instructions' => 'Store in cool, dry area. Avoid moisture exposure.',
    'usage' => 'Excellent for enriching soil in home gardens and pots.',
    'price' => 10.00,
    'original_price' => 13.00,
    'image' => 'products/vermicompost.jpeg',
    'stock' => 18,
    'category_slug' => 'soil-fertilizers',
],
[
    'name' => 'Cocopeat Brick (2.5 KG)',
    'description' => 'Eco-friendly growing medium made from compressed coconut fibers. Just soak to rehydrate and use as a base enhancer for soil. Retains moisture and improves aeration. Weight: 2.5 KG.',
    'care_instructions' => 'Keep in dry storage. Rehydrate only when ready to use.',
    'usage' => 'Use as a base soil enhancer after soaking in water.',
    'price' => 4.50,
    'original_price' => 6.50,
    'image' => 'products/cocopeat-brick.jpeg',
    'stock' => 40,
    'category_slug' => 'soil-fertilizers',
],
[
    'name' => 'Perlite Bag (2 KG)',
    'description' => 'Lightweight perlite soil additive to improve drainage and soil aeration. The 2 KG bag is perfect for mixing with potting soil to create a healthier root environment.',
    'care_instructions' => 'Seal bag tightly to prevent dust exposure.',
    'usage' => 'Mix with soil to improve aeration and drainage.',
    'price' => 5.00,
    'original_price' => 7.00,
    'image' => 'products/perlite-bag.jpeg',
    'stock' => 30,
    'category_slug' => 'soil-fertilizers',
],
[
    'name' => 'Bone Meal Fertilizer (2 KG)',
    'description' => 'Organic bone meal fertilizer that promotes strong root development. Ideal for use when planting bulbs, trees, and shrubs. A 2 KG bag packed with phosphorus and calcium.',
    'care_instructions' => 'Store away from pets. Keep in a sealed container.',
    'usage' => 'Best used during planting of bulbs, trees, and shrubs.',
    'price' => 6.00,
    'original_price' => 8.00,
    'image' => 'products/bone-meal.jpeg',
    'stock' => 18,
    'category_slug' => 'soil-fertilizers',
],
[
    'name' => 'Organic Compost Mix (5 KG)',
    'description' => 'Premium quality organic compost to naturally enrich your soil. Perfect for improving planting beds and conditioning soil. Comes in a 5 KG bag full of nutrients.',
    'care_instructions' => 'Keep bag sealed to retain nutrients. Store in shade.',
    'usage' => 'Use for soil conditioning and planting beds.',
    'price' => 8.00,
    'original_price' => 11.00,
    'image' => 'products/organic-compost-mix.jpg',
    'stock' => 20,
    'category_slug' => 'soil-fertilizers',
],

// seed
    
    [
        'name' => 'Sunflower Seeds (50g)',
        'description' => 'Grow bright and tall sunflowers easily at home. This packet contains approximately 50 grams of high-quality seeds ideal for sunny gardens or large containers. Sunflowers not only add vibrant beauty but also attract pollinators like bees.',
        'care_instructions' => 'Store in a cool, dry place away from sunlight. Ensure the packet is sealed after each use to maintain freshness and viability.',
        'usage' => 'Plant directly in sunny outdoor spots or large pots.',
        'price' => 3.00,
        'original_price' => 4.00,
        'image' => 'products/sunflower-seeds.jpg',
        'stock' => 50,
        'category_slug' => 'seeds',
    ],
    [
        'name' => 'Basil Seeds (20g)',
        'description' => 'Fresh basil seeds for aromatic herbs in your kitchen. This 20g packet offers plenty of seeds to grow flavorful and fragrant basil, perfect for cooking, garnishing, and teas.',
        'care_instructions' => 'Keep sealed in a dry, cool place to maintain freshness and prevent mold or pest contamination. Do not expose to humidity.',
        'usage' => 'Ideal for kitchen herb gardens or window boxes.',
        'price' => 2.00,
        'original_price' => 3.00,
        'image' => 'products/basil-seeds.jpg',
        'stock' => 40,
        'category_slug' => 'seeds',
    ],
    [
        'name' => 'Tomato Seeds (30g)',
        'description' => 'High-yield tomato seeds for home gardens. The 30g packet offers premium seeds for juicy, flavorful tomatoes. Ideal for growing a variety of dishes, from salads to sauces.',
        'care_instructions' => 'Store in a dark, dry space with good air circulation. Avoid high temperatures or moisture to preserve seed quality.',
        'usage' => 'Start indoors, then transplant outdoors in full sun.',
        'price' => 2.50,
        'original_price' => 3.50,
        'image' => 'products/tomato-seeds.jpg',
        'stock' => 45,
        'category_slug' => 'seeds',
    ],
    [
        'name' => 'Mint Seeds (20g)',
        'description' => 'Easy-to-grow mint seeds perfect for teas and dishes. The 20g packet yields aromatic mint for culinary and herbal uses, freshening your garden or kitchen.',
        'care_instructions' => 'Seal tightly and store in a dry cabinet away from direct heat. Use within a year for best results.',
        'usage' => 'Grow in containers or garden beds with partial sun.',
        'price' => 2.00,
        'original_price' => 3.00,
        'image' => 'products/mint-seeds.jpg',
        'stock' => 35,
        'category_slug' => 'seeds',
    ],
    [
        'name' => 'Carrot Seeds (30g)',
        'description' => 'Organic carrot seeds for a healthy vegetable garden. Each 30g packet contains seeds for sweet, crunchy carrots, rich in beta-carotene and essential nutrients.',
        'care_instructions' => 'Keep away from moisture and heat. Ensure the container is sealed and store in a dark location.',
        'usage' => 'Sow directly in well-drained soil outdoors.',
        'price' => 2.50,
        'original_price' => 4.00,
        'image' => 'products/carrot-seeds.jpg',
        'stock' => 30,
        'category_slug' => 'seeds',
    ],
    [
        'name' => 'Pepper Seeds (25g)',
        'description' => 'Sweet and spicy pepper seeds for all tastes. This 25g packet offers seeds for vibrant, flavorful peppers—ideal for stir-fries, salads, and sauces.',
        'care_instructions' => 'Store in an airtight bag in a dry, cool location. Keep out of direct sunlight and away from moisture.',
        'usage' => 'Start indoors, transplant after frost risk passes.',
        'price' => 2.50,
        'original_price' => 4.00,
        'image' => 'products/pepper-seeds.jpg',
        'stock' => 32,
        'category_slug' => 'seeds',
    ],
    [
        'name' => 'Strawberry Seeds (20g)',
        'description' => 'Grow sweet strawberries right from your garden. Each 20g packet contains premium seeds to produce juicy, red strawberries—great for desserts and snacks.',
        'care_instructions' => 'Refrigerate if not planting immediately. Ensure the packet is dry and well sealed before storage.',
        'usage' => 'Best started indoors, then transplanted to garden or pots.',
        'price' => 3.50,
        'original_price' => 5.00,
        'image' => 'products/strawberry-seeds.jpg',
        'stock' => 25,
        'category_slug' => 'seeds',
    ],
    [
        'name' => 'Lavender Seeds (20g)',
        'description' => 'Plant fragrant lavender flowers for relaxation and beauty. The 20g packet provides seeds for lush purple blooms, ideal for aromatherapy or garden borders.',
        'care_instructions' => 'Keep cool and dry; use within a year. Protect from humidity and heat for optimal viability.',
        'usage' => 'Sow in sunny spots or decorative pots.',
        'price' => 3.00,
        'original_price' => 4.00,
        'image' => 'products/lavender-seeds.jpg',
        'stock' => 28,
        'category_slug' => 'seeds',
    ],
    [
        'name' => 'Cucumber Seeds (30g)',
        'description' => 'Crispy and fresh cucumber seeds for garden lovers. Each 30g packet offers seeds for crunchy cucumbers, ideal for salads, pickling, and snacks.',
        'care_instructions' => 'Seal tightly and store away from humidity. Best kept in a dry box or drawer until use.',
        'usage' => 'Plant in warm soil with full sun.',
        'price' => 2.50,
        'original_price' => 4.00,
        'image' => 'products/cucumber-seeds.jpg',
        'stock' => 38,
        'category_slug' => 'seeds',
    ],


    
 //pots

   [
    'name' => 'Clay Pot Medium Size',
    'description' => 'Classic medium-sized clay pot, perfect for all types of plants. It provides excellent air circulation for the roots and enhances any décor. Dimensions: Height 20 cm, Diameter 22 cm.',
    'care_instructions' => 'Clean with water and mild soap. Avoid freezing temperatures.',
    'usage' => 'Suitable for indoor and outdoor plants. Add drainage layer before soil.',
    'price' => 4.00,
    'original_price' => 6.00,
    'image' => 'products/clay-pot.jpeg',
    'stock' => 20,
    'category_slug' => 'pots',
],
[
    'name' => 'Ceramic Planter',
    'description' => 'Beautiful ceramic planter for large plants and indoor trees. Adds elegance to any room. Dimensions: Height 25 cm, Diameter 24 cm.',
    'care_instructions' => 'Wipe with a damp cloth. Avoid dropping or harsh impacts.',
    'usage' => 'Ideal for big houseplants or decorative indoor trees.',
    'price' => 8.00,
    'original_price' => 12.00,
    'image' => 'products/ceramic-planter.jpeg',
    'stock' => 10,
    'category_slug' => 'pots',
],
[
    'name' => 'Hanging Pot Set',
    'description' => 'Set of 3 hanging pots for balconies and patios. Great for small spaces. Dimensions: Height 15 cm, Diameter 17 cm (each).',
    'care_instructions' => 'Check the hanging cords regularly. Clean with soft cloth.',
    'usage' => 'Hang on balcony railings or ceiling hooks. Best for trailing plants.',
    'price' => 6.00,
    'original_price' => 8.00,
    'image' => 'products/hanging-pot.jpeg',
    'stock' => 12,
    'category_slug' => 'pots',
],
[
    'name' => 'Decorative Plastic Pot',
    'description' => 'Lightweight and colorful pot perfect for decorative plants. Easy to move and clean. Dimensions: Height 18 cm, Diameter 20 cm.',
    'care_instructions' => 'Wash with water. Avoid direct sun to prevent fading.',
    'usage' => 'Great for lightweight plants. Use indoors or on shelves.',
    'price' => 3.50,
    'original_price' => 5.00,
    'image' => 'products/plastic-pot.jpeg',
    'stock' => 30,
    'category_slug' => 'pots',
],
[
    'name' => 'Modern Metal Planter',
    'description' => 'Stylish metal planter for modern interiors. Minimalist and chic. Dimensions: Height 23 cm, Diameter 22 cm.',
    'care_instructions' => 'Wipe with dry cloth. Keep away from water to avoid rust.',
    'usage' => 'Perfect for minimalist indoor designs. Use with plastic inner pot.',
    'price' => 10.00,
    'original_price' => 15.00,
    'image' => 'products/metal-planter.jpeg',
    'stock' => 8,
    'category_slug' => 'pots',
],
[
    'name' => 'Terracotta Pot',
    'description' => 'Classic clay pot for any plant type. Porous material allows air flow. Dimensions: Height 21 cm, Diameter 22 cm.',
    'care_instructions' => 'Soak before use. Clean with brush. Store indoors in winter.',
    'usage' => 'Ideal for herbs and flowering plants. Allows natural aeration.',
    'price' => 5.00,
    'original_price' => 7.00,
    'image' => 'products/terracotta-pot.jpeg',
    'stock' => 40,
    'category_slug' => 'pots',
],
[
    'name' => 'Self-Watering Planter',
    'description' => 'Smart pot with a self-watering system. Ideal for busy plant lovers. Dimensions: Height 22 cm, Diameter 21 cm.',
    'care_instructions' => 'Clean the water reservoir monthly. Avoid algae buildup.',
    'usage' => 'Perfect for busy plant owners. Fill reservoir every few days.',
    'price' => 7.50,
    'original_price' => 10.00,
    'image' => 'products/self-watering-planter.jpeg',
    'stock' => 20,
    'category_slug' => 'pots',
],
[
    'name' => 'Concrete Planter',
    'description' => 'Modern stylish planter for indoor & outdoor use. Very durable and heavy. Dimensions: Height 24 cm, Diameter 25 cm.',
    'care_instructions' => 'Avoid dropping. Clean with a damp cloth. Seal if needed.',
    'usage' => 'Use for large plants or decorative displays. Heavy and stable.',
    'price' => 8.00,
    'original_price' => 10.00,
    'image' => 'products/concrete-planter.jpeg',
    'stock' => 15,
    'category_slug' => 'pots',
],
[
    'name' => 'Hanging Basket',
    'description' => 'Perfect for small balconies and patios. Decorative and functional. Dimensions: Height 16 cm, Diameter 20 cm.',
    'care_instructions' => 'Keep cords dry. Remove and clean basket monthly.',
    'usage' => 'Ideal for flowering or trailing plants. Hang in partial sun.',
    'price' => 9.00,
    'original_price' => 11.00,
    'image' => 'products/hanging-basket.jpeg',
    'stock' => 25,
    'category_slug' => 'pots',
],

    

// kids garden 
[
    'name' => 'Kids Mini Watering Can - Small Size',
    'description' => 'Colorful and lightweight watering can designed perfectly for little hands. Encourages kids to enjoy watering plants and develop a love for gardening. Ideal for indoor or outdoor plant care.',
    'care_instructions' => 'Rinse after use and store indoors.',
    'usage' => 'Use for watering small pots or garden beds.',
    'price' => 2.00,
    'original_price' => 5.00,
    'image' => 'products/kids-watering-can1.jpeg',
    'stock' => 30,
    'category_slug' => 'kids-gardening',
],
[
    'name' => 'Children Gardening Gloves',
    'description' => 'Soft, flexible, and durable gloves to protect little gardeners from dirt, scratches, and bugs. Designed to fit small hands comfortably with fun colors.',
    'care_instructions' => 'Hand wash and air dry.',
    'usage' => 'Wear during gardening activities or when handling soil and plants.',
    'price' => 3.50,
    'original_price' => 5.00,
    'image' => 'products/kids-gardening-gloves.jpeg',
    'stock' => 40,
    'category_slug' => 'kids-gardening',
],
[
    'name' => 'Kids Gardening Tool Set',
    'description' => 'A colorful mini tool set including a shovel, rake, and trowel. Made of durable plastic and designed for small hands to dig, plant, and explore.',
    'care_instructions' => 'Clean tools after use and store safely.',
    'usage' => 'Use for planting seeds, digging soil, or playing in the garden.',
    'price' => 8.00,
    'original_price' => 12.00,
    'image' => 'products/kids-tool-set.jpeg',
    'stock' => 25,
    'category_slug' => 'kids-gardening',
],
[
    'name' => 'Flower Growing Kit for Kids',
    'description' => 'A complete kit for kids to grow their own flowers at home. Includes flower seeds, mini pots, soil pellets, and plant markers. Encourages learning, responsibility, and fun.',
    'care_instructions' => 'Keep soil moist and place in a sunny area.',
    'usage' => 'Follow instructions to plant, water, and watch the flowers grow.',
    'price' => 10.00,
    'original_price' => 12.00,
    'image' => 'products/kids-flower-growing-kit.jpeg',
    'stock' => 18,
    'category_slug' => 'kids-gardening',
],
[
    'name' => 'Kids Mini Watering Can',
    'description' => 'Compact and colorful watering can perfect for kids to help with plant care. Lightweight design and easy grip handle make it ideal for small hands.',
    'care_instructions' => 'Rinse with water and store after use.',
    'usage' => 'Use to water plants in pots or garden beds.',
    'price' => 2.00,
    'original_price' => 5.00,
    'image' => 'products/kids-watering-can.jpeg',
    'stock' => 30,
    'category_slug' => 'kids-gardening',
],
[
    'name' => 'Mini Plant Pots for Kids',
    'description' => 'Set of colorful small pots designed for kids\' gardening projects. Perfect for planting herbs, flowers, or small veggies indoors or outdoors.',
    'care_instructions' => 'Clean with water. Avoid dropping.',
    'usage' => 'Use for growing small plants. Paintable surface for added fun.',
    'price' => 3.00,
    'original_price' => 5.00,
    'image' => 'products/kids-mini-pots.jpeg',
    'stock' => 30,
    'category_slug' => 'kids-gardening',
],
[
    'name' => 'Kids Grow Your Own Vegetables Kit',
    'description' => 'Fun vegetable growing kit to teach kids how to grow their own food. Includes seed packets (carrot, tomato, lettuce), soil discs, biodegradable pots, plant markers, and a guide.',
    'care_instructions' => 'Water daily and place in sunlight.',
    'usage' => 'Perfect for learning how vegetables grow from seed to harvest.',
    'price' => 8.00,
    'original_price' => 10.00,
    'image' => 'products/kids-vegetable-growing-kit.jpeg',
    'stock' => 22,
    'category_slug' => 'kids-gardening',
],
[
    'name' => 'Paint Your Own Flower Pot Kit',
    'description' => 'A creative kit that lets kids paint and decorate their own flower pots. Includes a ceramic pot, paint colors, brushes, and design ideas. Encourages artistic expression and gardening interest.',
    'care_instructions' => 'Let paint dry before use. Clean brushes after painting.',
    'usage' => 'Paint the pot, let it dry, then plant seeds or flowers.',
    'price' => 7.50,
    'original_price' => 9.00,
    'image' => 'products/kids-paint-flower-pot.jpeg',
    'stock' => 20,
    'category_slug' => 'kids-gardening',
],
[
    'name' => 'Little Gardeners Starter Kit',
    'description' => 'This complete starter kit is perfect for young kids beginning their gardening journey. Includes a mini watering can, gloves, shovel, seeds, soil discs, plant markers, and a colorful carry bag.',
    'care_instructions' => 'Clean tools and store them after use. Keep seeds in a cool, dry place.',
    'usage' => 'Follow the guide to plant seeds, care for them, and enjoy watching them grow.',
    'price' => 10.00,
    'original_price' => 12.00,
    'image' => 'products/kids-gardener-starter-kit.jpg',
    'stock' => 15,
    'category_slug' => 'kids-gardening',
],
     
            
            
        ];

        foreach ($products as $productData) {
            $category = Category::where('slug', $productData['category_slug'])->first();
            if ($category) {
                Product::create([
                    'name' => $productData['name'],
                    'slug' => Str::slug($productData['name']),
                    'description' => $productData['description'],
                    'care_instructions' => $productData['care_instructions'] ?? null, // إضافة طريقة العناية
                    'usage' => $productData['usage'] ?? null, // إضافة طريقة الاستخدام
                    'price' => $productData['price'],
                    'original_price' => $productData['original_price'] ?? null,
                    'image' => $productData['image'],
                    'images' => $productData['images'] ?? null, // إضافة الصور المتعددة (اختياري)
                    'is_featured' => rand(0, 1),
                    'is_hot' => rand(0, 1),
                    'is_on_sale' => rand(0, 1),
                    'stock' => $productData['stock'],
                    'category_id' => $category->id,
                ]);
            }
        }
        
    }
}
